export enum ROUTES_ENUM {
  HOME = "/",
  ACTIVITY = "/activity",
  CONTACTS = "/contacts",
  DEMINING = "/demining",
  ADMIN = "/admin",
  ADMIN_PARTNERS = "/admin-panel/partners",
  ADMIN_OUR_CONTACTS = "/admin-panel/contacts",
  ADMIN_FEEDBACK = "/admin-panel/feedback",
  FEEDBACK_DETAILS = ":id",
  ADMIN_REPORTS = "/admin-panel/reports",
  AUTH = "/auth",
  RESTORE = "/auth/restore",
  NEW_PASSWORD = "/auth/new-password",
  NOT_FOUND = "/*",
}
